/*
* Generated file
*
* Generated from: yang module name: statistics-manager yang module local name: statistics-manager
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:55 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.statistics_manager;
public interface StatisticsManagerModuleMXBean {
    public javax.management.ObjectName getNotificationService();

    public void setNotificationService(javax.management.ObjectName notificationService);

    public javax.management.ObjectName getRpcRegistry();

    public void setRpcRegistry(javax.management.ObjectName rpcRegistry);

    public javax.management.ObjectName getDataBroker();

    public void setDataBroker(javax.management.ObjectName dataBroker);

    public org.opendaylight.controller.config.yang.md.sal.statistics_manager.StatisticsManagerSettings getStatisticsManagerSettings();

    public void setStatisticsManagerSettings(org.opendaylight.controller.config.yang.md.sal.statistics_manager.StatisticsManagerSettings statisticsManagerSettings);

}
