/*
* Generated file
*
* Generated from: yang module name: statistics-manager yang module local name: statistics-manager
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:55 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.statistics_manager;
public class StatisticsManagerSettings {
    private org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;

    private java.lang.Integer maxNodesForCollector;

    private java.lang.Integer minRequestNetMonitorInterval;

    public StatisticsManagerSettings () {
        super();
    }

    public void injectDependencyResolver(org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.dependencyResolver = dependencyResolver;
    }

    public java.lang.Integer getMaxNodesForCollector() {
        return maxNodesForCollector;
    }

    public void setMaxNodesForCollector(java.lang.Integer maxNodesForCollector) {
        this.maxNodesForCollector = maxNodesForCollector;
    }

    public java.lang.Integer getMinRequestNetMonitorInterval() {
        return minRequestNetMonitorInterval;
    }

    public void setMinRequestNetMonitorInterval(java.lang.Integer minRequestNetMonitorInterval) {
        this.minRequestNetMonitorInterval = minRequestNetMonitorInterval;
    }

}
