/*
* Generated file
*
* Generated from: yang module name: opendaylight-md-sal-binding yang module local name: binding-async-data-broker
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:07 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.binding;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding?revision=2013-10-28)binding-async-data-broker", osgiRegistrationType = org.opendaylight.controller.md.sal.binding.api.DataBroker.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding", revision = "2013-10-28", localName = "binding-async-data-broker")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding", revision = "2013-10-28", name = "opendaylight-md-sal-binding")

public interface DataBrokerServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
