/*
* Generated file
*
* Generated from: yang module name: config-test-impl yang module local name: impl-netconf
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:41:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.test.impl;
@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(revision = "2013-04-03", name = "config-test-impl", namespace = "urn:opendaylight:params:xml:ns:yang:controller:test:impl")

public abstract class AbstractNetconfTestImplModuleFactory implements org.opendaylight.controller.config.spi.ModuleFactory {
    public static final java.lang.String NAME = "impl-netconf";

    private static final java.util.Set<Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface>> serviceIfcs;

    @Override
    public final String getImplementationName() {
        return NAME;
    }

    static {
        java.util.Set<Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface>> serviceIfcs2 = new java.util.HashSet<Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface>>();
        serviceIfcs2.add(org.opendaylight.controller.config.yang.test.AutoCloseableServiceInterface.class);
        serviceIfcs = java.util.Collections.unmodifiableSet(serviceIfcs2);
    }

    @Override
    public final boolean isModuleImplementingServiceInterface(Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface> serviceInterface) {
        for (Class<?> ifc: serviceIfcs) {
            if (serviceInterface.isAssignableFrom(ifc)){
                return true;
            }
        }
        return false;
    }

    @Override
    public java.util.Set<Class<? extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface>> getImplementedServiceIntefaces() {
        return serviceIfcs;
    }

    @Override
    public org.opendaylight.controller.config.spi.Module createModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, org.osgi.framework.BundleContext bundleContext) {
        return instantiateModule(instanceName, dependencyResolver, bundleContext);
    }

    @Override
    public org.opendaylight.controller.config.spi.Module createModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, org.opendaylight.controller.config.api.DynamicMBeanWithInstance old, org.osgi.framework.BundleContext bundleContext) throws Exception {
        org.opendaylight.controller.config.yang.test.impl.NetconfTestImplModule oldModule = null;
        try {
            oldModule = (org.opendaylight.controller.config.yang.test.impl.NetconfTestImplModule) old.getModule();
        } catch(Exception e) {
            return handleChangedClass(old);
        }
        org.opendaylight.controller.config.yang.test.impl.NetconfTestImplModule module = instantiateModule(instanceName, dependencyResolver, oldModule, old.getInstance(), bundleContext);
        module.setSimpleLong2(oldModule.getSimpleLong2());
        module.setTestingDeps(oldModule.getTestingDeps());
        module.setBinaryLeaf(oldModule.getBinaryLeaf());
        module.setComplexList(oldModule.getComplexList());
        module.setExtended(oldModule.getExtended());
        module.setSimpleInt(oldModule.getSimpleInt());
        module.setExtendedEnum(oldModule.getExtendedEnum());
        module.setType(oldModule.getType());
        module.setSimpleList(oldModule.getSimpleList());
        module.setExtendedTwice(oldModule.getExtendedTwice());
        module.setSleepFactor(oldModule.getSleepFactor());
        module.setDtoD(oldModule.getDtoD());
        module.setSimpleTest(oldModule.getSimpleTest());
        module.setIp(oldModule.getIp());
        module.setUnionTestAttr(oldModule.getUnionTestAttr());
        module.setDtoC(oldModule.getDtoC());
        module.setSimpleLong(oldModule.getSimpleLong());
        module.setSimpleBoolean(oldModule.getSimpleBoolean());
        module.setSimpleShort(oldModule.getSimpleShort());
        module.setSimpleBigInteger(oldModule.getSimpleBigInteger());
        module.setPeers(oldModule.getPeers());
        module.setSimpleByte(oldModule.getSimpleByte());
        module.setTestingDep(oldModule.getTestingDep());

        return module;
    }

    public org.opendaylight.controller.config.yang.test.impl.NetconfTestImplModule instantiateModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, org.opendaylight.controller.config.yang.test.impl.NetconfTestImplModule oldModule, java.lang.AutoCloseable oldInstance, org.osgi.framework.BundleContext bundleContext) {
        return new org.opendaylight.controller.config.yang.test.impl.NetconfTestImplModule(new org.opendaylight.controller.config.api.ModuleIdentifier(NAME, instanceName), dependencyResolver, oldModule, oldInstance);
    }

    public org.opendaylight.controller.config.yang.test.impl.NetconfTestImplModule instantiateModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, org.osgi.framework.BundleContext bundleContext) {
        return new org.opendaylight.controller.config.yang.test.impl.NetconfTestImplModule(new org.opendaylight.controller.config.api.ModuleIdentifier(NAME, instanceName), dependencyResolver);
    }

    public org.opendaylight.controller.config.yang.test.impl.NetconfTestImplModule handleChangedClass(org.opendaylight.controller.config.api.DynamicMBeanWithInstance old) throws Exception {
        throw new UnsupportedOperationException("Class reloading is not supported");
    }

    @Override
    public java.util.Set<org.opendaylight.controller.config.yang.test.impl.NetconfTestImplModule> getDefaultModules(org.opendaylight.controller.config.api.DependencyResolverFactory dependencyResolverFactory, org.osgi.framework.BundleContext bundleContext) {
        return new java.util.HashSet<org.opendaylight.controller.config.yang.test.impl.NetconfTestImplModule>();
    }

}
