/*
* Generated file
*
* Generated from: yang module name: config-test-impl yang module local name: impl-netconf
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:41:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.test.impl;
public class ComplexList {
    private org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;

    private java.util.List<org.opendaylight.controller.config.yang.test.impl.SimpleList> simpleList;

    public ComplexList () {
        super();
    }

    public void injectDependencyResolver(org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.dependencyResolver = dependencyResolver;
    }

    public java.util.List<org.opendaylight.controller.config.yang.test.impl.SimpleList> getSimpleList() {
        return simpleList;
    }

    public void setSimpleList(java.util.List<org.opendaylight.controller.config.yang.test.impl.SimpleList> simpleList) {
        this.simpleList = simpleList;
    }

}
