/*
* Generated file
*
* Generated from: yang module name: config-test-impl yang module local name: impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:41:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.test.impl;
public class DtoB {
    private org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;

    private java.lang.Long simpleInt2;

    private java.lang.Long simpleInt1 = new java.lang.Long("32");

    public DtoB () {
        super();
    }

    public void injectDependencyResolver(org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.dependencyResolver = dependencyResolver;
    }

    public java.lang.Long getSimpleInt2() {
        return simpleInt2;
    }

    public void setSimpleInt2(java.lang.Long simpleInt2) {
        this.simpleInt2 = simpleInt2;
    }

    public java.lang.Long getSimpleInt1() {
        return simpleInt1;
    }

    public void setSimpleInt1(java.lang.Long simpleInt1) {
        this.simpleInt1 = simpleInt1;
    }

}
