/*
* Generated file
*
* Generated from: yang module name: config-test-impl yang module local name: impl-netconf
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:41:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.test.impl;
public class DtoC {
    private org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;

    private java.lang.Long simpleArg;

    private org.opendaylight.controller.config.yang.test.impl.DtoAInner dtoAInner;

    public DtoC () {
        super();
    }

    public void injectDependencyResolver(org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.dependencyResolver = dependencyResolver;
    }

    public java.lang.Long getSimpleArg() {
        return simpleArg;
    }

    public void setSimpleArg(java.lang.Long simpleArg) {
        this.simpleArg = simpleArg;
    }

    public org.opendaylight.controller.config.yang.test.impl.DtoAInner getDtoAInner() {
        return dtoAInner;
    }

    public void setDtoAInner(org.opendaylight.controller.config.yang.test.impl.DtoAInner dtoAInner) {
        this.dtoAInner = dtoAInner;
    }

}
