/*
* Generated file
*
* Generated from: yang module name: config-test-impl yang module local name: impl-identity-test
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:41:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.test.impl;
public interface IdentityTestModuleMXBean {
    public org.opendaylight.controller.config.yang.test.impl.IdentitiesContainer getIdentitiesContainer();

    public void setIdentitiesContainer(org.opendaylight.controller.config.yang.test.impl.IdentitiesContainer identitiesContainer);

    public java.util.List<org.opendaylight.controller.config.yang.test.impl.Identities> getIdentities();

    public void setIdentities(java.util.List<org.opendaylight.controller.config.yang.test.impl.Identities> identities);

    public org.opendaylight.controller.config.api.IdentityAttributeRef getAfi();

    public void setAfi(org.opendaylight.controller.config.api.IdentityAttributeRef afi);

}
