/*
* Generated file
*
* Generated from: yang module name: config-test-impl yang module local name: impl-identity-test
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:41:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.test.impl;
public class IdentitiesInner {
    private org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;

    private org.opendaylight.controller.config.api.IdentityAttributeRef afi;

    public IdentitiesInner () {
        super();
    }

    public void injectDependencyResolver(org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.dependencyResolver = dependencyResolver;
    }

    public java.lang.Class<? extends org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.controller.config.test.types.rev131127.TestIdentity1> resolveAfi() {
        return afi.resolveIdentity(dependencyResolver,org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.controller.config.test.types.rev131127.TestIdentity1.class);
    }

    public org.opendaylight.controller.config.api.IdentityAttributeRef getAfi() {
        return afi;
    }

    public void setAfi(org.opendaylight.controller.config.api.IdentityAttributeRef afi) {
        this.afi = afi;
    }

}
