/*
* Generated file
*
* Generated from: yang module name: config-test-impl yang module local name: multiple-dependencies
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:41:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.test.impl;
public interface MultipleDependenciesModuleMXBean {
    public java.util.List<javax.management.ObjectName> getTestingDeps();

    public void setTestingDeps(java.util.List<javax.management.ObjectName> testingDeps);

}
