/*
* Generated file
*
* Generated from: yang module name: config-test-impl yang module local name: impl-netconf
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:41:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.test.impl;
public interface NetconfTestImplModuleMXBean {
    public java.lang.Long getSimpleLong2();

    public void setSimpleLong2(java.lang.Long simpleLong2);

    public java.util.List<javax.management.ObjectName> getTestingDeps();

    public void setTestingDeps(java.util.List<javax.management.ObjectName> testingDeps);

    public byte[] getBinaryLeaf();

    public void setBinaryLeaf(byte[] binaryLeaf);

    public java.util.List<org.opendaylight.controller.config.yang.test.impl.ComplexList> getComplexList();

    public void setComplexList(java.util.List<org.opendaylight.controller.config.yang.test.impl.ComplexList> complexList);

    public org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.controller.config.test.types.rev131127.ExtendOnce getExtended();

    public void setExtended(org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.controller.config.test.types.rev131127.ExtendOnce extended);

    public java.lang.Long getSimpleInt();

    public void setSimpleInt(java.lang.Long simpleInt);

    public org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.controller.config.test.types.rev131127.ExtendEnum getExtendedEnum();

    public void setExtendedEnum(org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.controller.config.test.types.rev131127.ExtendEnum extendedEnum);

    public java.lang.String getType();

    public void setType(java.lang.String type);

    public java.util.List<java.lang.Integer> getSimpleList();

    public void setSimpleList(java.util.List<java.lang.Integer> simpleList);

    public org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.controller.config.test.types.rev131127.ExtendTwice getExtendedTwice();

    public void setExtendedTwice(org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.controller.config.test.types.rev131127.ExtendTwice extendedTwice);

    public java.math.BigDecimal getSleepFactor();

    public void setSleepFactor(java.math.BigDecimal sleepFactor);

    public org.opendaylight.controller.config.yang.test.impl.DtoD getDtoD();

    public void setDtoD(org.opendaylight.controller.config.yang.test.impl.DtoD dtoD);

    public java.lang.Integer getSimpleTest();

    public void setSimpleTest(java.lang.Integer simpleTest);

    public org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.inet.types.rev100924.IpAddress getIp();

    public void setIp(org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.inet.types.rev100924.IpAddress ip);

    public org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.controller.config.test.types.rev131127.UnionTest getUnionTestAttr();

    public void setUnionTestAttr(org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.controller.config.test.types.rev131127.UnionTest unionTestAttr);

    public org.opendaylight.controller.config.yang.test.impl.DtoC getDtoC();

    public void setDtoC(org.opendaylight.controller.config.yang.test.impl.DtoC dtoC);

    public java.lang.Long getSimpleLong();

    public void setSimpleLong(java.lang.Long simpleLong);

    public java.lang.Boolean getSimpleBoolean();

    public void setSimpleBoolean(java.lang.Boolean simpleBoolean);

    public java.lang.Short getSimpleShort();

    public void setSimpleShort(java.lang.Short simpleShort);

    public java.math.BigInteger getSimpleBigInteger();

    public void setSimpleBigInteger(java.math.BigInteger simpleBigInteger);

    public java.util.List<org.opendaylight.controller.config.yang.test.impl.Peers> getPeers();

    public void setPeers(java.util.List<org.opendaylight.controller.config.yang.test.impl.Peers> peers);

    public java.lang.Byte getSimpleByte();

    public void setSimpleByte(java.lang.Byte simpleByte);

    public javax.management.ObjectName getTestingDep();

    public void setTestingDep(javax.management.ObjectName testingDep);

}
