/*
* Generated file
*
* Generated from: yang module name: config-test-impl yang module local name: impl-netconf
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:41:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.test.impl;
public class Peers {
    private org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;

    private java.lang.String port;

    private java.lang.Integer simpleInt3;

    private java.lang.Long coreSize;

    public Peers () {
        super();
    }

    public void injectDependencyResolver(org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.dependencyResolver = dependencyResolver;
    }

    public java.lang.String getPort() {
        return port;
    }

    public void setPort(java.lang.String port) {
        this.port = port;
    }

    public java.lang.Integer getSimpleInt3() {
        return simpleInt3;
    }

    public void setSimpleInt3(java.lang.Integer simpleInt3) {
        this.simpleInt3 = simpleInt3;
    }

    public java.lang.Long getCoreSize() {
        return coreSize;
    }

    public void setCoreSize(java.lang.Long coreSize) {
        this.coreSize = coreSize;
    }

}
