/*
* Generated file
*
* Generated from: yang module name: config-test-impl yang module local name: impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:41:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.test.impl;
public interface TestImplModuleMXBean {
    public org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.inet.types.rev100924.AsNumber getAsNumber();

    public void setAsNumber(org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.inet.types.rev100924.AsNumber asNumber);

    public org.opendaylight.controller.config.yang.test.impl.DtoA getDtoA();

    public void setDtoA(org.opendaylight.controller.config.yang.test.impl.DtoA dtoA);

    public org.opendaylight.controller.config.yang.test.impl.DtoB getDtoB();

    public void setDtoB(org.opendaylight.controller.config.yang.test.impl.DtoB dtoB);

    public java.lang.Long getSimpleInt();

    public void setSimpleInt(java.lang.Long simpleInt);

    public java.util.List<java.lang.String> getAllowUser();

    /**
    * A list of user name patterns to allow
    */
    public void setAllowUser(java.util.List<java.lang.String> allowUser);

}
