/*
* Generated file
*
* Generated from: yang module name: protocol-framework yang module local name: reconnect-immediately-strategy-factory
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat May 16 20:48:52 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.protocol.framework;
@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(revision = "2014-03-13", name = "protocol-framework", namespace = "urn:opendaylight:params:xml:ns:yang:controller:protocol:framework")

public abstract class AbstractReconnectImmediatelyStrategyFactoryModule implements org.opendaylight.controller.config.spi.Module,org.opendaylight.controller.config.yang.protocol.framework.ReconnectImmediatelyStrategyFactoryModuleMXBean,org.opendaylight.controller.config.yang.protocol.framework.ReconnectStrategyFactoryServiceInterface {
    private static final org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(org.opendaylight.controller.config.yang.protocol.framework.AbstractReconnectImmediatelyStrategyFactoryModule.class);

    //attributes start

    public static final org.opendaylight.controller.config.api.JmxAttribute reconnectExecutorJmxAttribute = new org.opendaylight.controller.config.api.JmxAttribute("ReconnectExecutor");
    private javax.management.ObjectName reconnectExecutor; // mandatory

    public static final org.opendaylight.controller.config.api.JmxAttribute reconnectTimeoutJmxAttribute = new org.opendaylight.controller.config.api.JmxAttribute("ReconnectTimeout");
    private java.lang.Integer reconnectTimeout;

    //attributes end

    private final AbstractReconnectImmediatelyStrategyFactoryModule oldModule;
    private final java.lang.AutoCloseable oldInstance;
    private java.lang.AutoCloseable instance;
    protected final org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;
    private final org.opendaylight.controller.config.api.ModuleIdentifier identifier;
    @Override
    public org.opendaylight.controller.config.api.ModuleIdentifier getIdentifier() {
        return identifier;
    }

    public AbstractReconnectImmediatelyStrategyFactoryModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier,org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.identifier = identifier;
        this.dependencyResolver = dependencyResolver;
        this.oldInstance=null;
        this.oldModule=null;
    }

    public AbstractReconnectImmediatelyStrategyFactoryModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier,org.opendaylight.controller.config.api.DependencyResolver dependencyResolver,AbstractReconnectImmediatelyStrategyFactoryModule oldModule,java.lang.AutoCloseable oldInstance) {
        this.identifier = identifier;
        this.dependencyResolver = dependencyResolver;
        this.oldModule = oldModule;
        this.oldInstance = oldInstance;
    }

    @Override
    public void validate() {
        dependencyResolver.validateDependency(org.opendaylight.controller.config.yang.netty.EventExecutorServiceInterface.class, reconnectExecutor, reconnectExecutorJmxAttribute);
        customValidation();
    }

    protected void customValidation() {
    }

    private io.netty.util.concurrent.EventExecutor reconnectExecutorDependency;
    protected final io.netty.util.concurrent.EventExecutor getReconnectExecutorDependency(){
        return reconnectExecutorDependency;
    }

    @Override
    public final java.lang.AutoCloseable getInstance() {
        if(instance==null) {
            reconnectExecutorDependency = dependencyResolver.resolveInstance(io.netty.util.concurrent.EventExecutor.class, reconnectExecutor, reconnectExecutorJmxAttribute);
            if(oldInstance!=null && canReuseInstance(oldModule)) {
                instance = reuseInstance(oldInstance);
            } else {
                if(oldInstance!=null) {
                    try {
                        oldInstance.close();
                    } catch(Exception e) {
                        logger.error("An error occurred while closing old instance " + oldInstance, e);
                    }
                }
                instance = createInstance();
                if (instance == null) {
                    throw new IllegalStateException("Error in createInstance - null is not allowed as return value");
                }
            }
        }
        return instance;
    }
    public abstract java.lang.AutoCloseable createInstance();

    public boolean canReuseInstance(AbstractReconnectImmediatelyStrategyFactoryModule oldModule){
        // allow reusing of old instance if no parameters was changed
        return isSame(oldModule);
    }

    public java.lang.AutoCloseable reuseInstance(java.lang.AutoCloseable oldInstance){
        // implement if instance reuse should be supported. Override canReuseInstance to change the criteria.
        return oldInstance;
    }

    public boolean isSame(AbstractReconnectImmediatelyStrategyFactoryModule other) {
        if (other == null) {
            throw new IllegalArgumentException("Parameter 'other' is null");
        }
        if (reconnectExecutorDependency != other.reconnectExecutorDependency) { // reference to dependency must be same
            return false;
        }
        if (java.util.Objects.deepEquals(reconnectTimeout, other.reconnectTimeout) == false) {
            return false;
        }

        return true;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AbstractReconnectImmediatelyStrategyFactoryModule that = (AbstractReconnectImmediatelyStrategyFactoryModule) o;
        return identifier.equals(that.identifier);
    }

    @Override
    public int hashCode() {
        return identifier.hashCode();
    }

    // getters and setters
    @Override
    public javax.management.ObjectName getReconnectExecutor() {
        return reconnectExecutor;
    }

    @Override
    @org.opendaylight.controller.config.api.annotations.RequireInterface(value = org.opendaylight.controller.config.yang.netty.EventExecutorServiceInterface.class)
    public void setReconnectExecutor(javax.management.ObjectName reconnectExecutor) {
        this.reconnectExecutor = reconnectExecutor;
    }

    @Override
    public java.lang.Integer getReconnectTimeout() {
        return reconnectTimeout;
    }

    @Override
    public void setReconnectTimeout(java.lang.Integer reconnectTimeout) {
        this.reconnectTimeout = reconnectTimeout;
    }

}
