/*
* Generated file
*
* Generated from: yang module name: protocol-framework yang module local name: never-reconnect-strategy-factory
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat May 16 20:48:52 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.protocol.framework;
public interface NeverReconnectStrategyFactoryModuleMXBean {
    public javax.management.ObjectName getExecutor();

    public void setExecutor(javax.management.ObjectName executor);

    public java.lang.Integer getTimeout();

    public void setTimeout(java.lang.Integer timeout);

}
