/*
* Generated file
*
* Generated from: yang module name: protocol-framework yang module local name: reconnect-immediately-strategy-factory
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat May 16 20:48:52 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.protocol.framework;
public interface ReconnectImmediatelyStrategyFactoryModuleMXBean {
    public javax.management.ObjectName getReconnectExecutor();

    public void setReconnectExecutor(javax.management.ObjectName reconnectExecutor);

    public java.lang.Integer getReconnectTimeout();

    public void setReconnectTimeout(java.lang.Integer reconnectTimeout);

}
