/*
* Generated file
*
* Generated from: yang module name: protocol-framework yang module local name: reconnect-strategy-factory
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat May 16 20:48:51 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.protocol.framework;
/**
* Service representing a reconnect strategy factory.
*/
@org.opendaylight.controller.config.api.annotations.Description(value = "Service representing a reconnect strategy factory.")

@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:protocol:framework?revision=2014-03-13)reconnect-strategy-factory", osgiRegistrationType = org.opendaylight.protocol.framework.ReconnectStrategyFactory.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:protocol:framework", revision = "2014-03-13", localName = "reconnect-strategy-factory")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:protocol:framework", revision = "2014-03-13", name = "protocol-framework")

public interface ReconnectStrategyFactoryServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
