/*
* Generated file
*
* Generated from: yang module name: protocol-framework yang module local name: timed-reconnect-strategy-factory
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat May 16 20:48:51 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.protocol.framework;
public interface TimedReconnectStrategyFactoryModuleMXBean {
    public java.lang.Integer getConnectTime();

    public void setConnectTime(java.lang.Integer connectTime);

    public java.lang.Long getMaxSleep();

    public void setMaxSleep(java.lang.Long maxSleep);

    public java.lang.Long getMinSleep();

    public void setMinSleep(java.lang.Long minSleep);

    public javax.management.ObjectName getTimedReconnectExecutor();

    public void setTimedReconnectExecutor(javax.management.ObjectName timedReconnectExecutor);

    public java.lang.Long getMaxAttempts();

    public void setMaxAttempts(java.lang.Long maxAttempts);

    public java.math.BigDecimal getSleepFactor();

    public void setSleepFactor(java.math.BigDecimal sleepFactor);

    public java.lang.Long getDeadline();

    public void setDeadline(java.lang.Long deadline);

}
