/*
* Generated file
*
* Generated from: yang module name: opendaylight-sal-binding-broker-impl yang module local name: binding-dom-mapping-service
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:34 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.binding.impl;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding:impl?revision=2013-10-28)binding-dom-mapping-service", osgiRegistrationType = org.opendaylight.controller.md.sal.binding.impl.BindingToNormalizedNodeCodec.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding:impl", revision = "2013-10-28", localName = "binding-dom-mapping-service")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding:impl", revision = "2013-10-28", name = "opendaylight-sal-binding-broker-impl")

public interface BindingToNormalizedNodeCodecServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
