/*
* Generated file
*
* Generated from: yang module name: opendaylight-sal-binding-broker-impl yang module local name: binding-data-compatible-broker
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:34 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.binding.impl;
public interface ForwardedCompatibleDataBrokerImplModuleMXBean {
    public javax.management.ObjectName getBindingMappingService();

    public void setBindingMappingService(javax.management.ObjectName bindingMappingService);

    public javax.management.ObjectName getDomAsyncBroker();

    public void setDomAsyncBroker(javax.management.ObjectName domAsyncBroker);

}
