/*
* Generated file
*
* Generated from: yang module name: config-test yang module local name: testing
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:41:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.test;
/**
* Test api
*/
@org.opendaylight.controller.config.api.annotations.Description(value = "Test api")

@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:test?revision=2013-06-13)testing", osgiRegistrationType = java.lang.AutoCloseable.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:test", revision = "2013-06-13", localName = "testing")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:test", revision = "2013-06-13", name = "config-test")

public interface AutoCloseableServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
