/*
* Generated file
*
* Generated from: yang module name: opendaylight-rest-connector yang module local name: rest-connector-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:38 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.rest.connector;
public interface RestConnectorModuleMXBean {
    public javax.management.ObjectName getDomBroker();

    public void setDomBroker(javax.management.ObjectName domBroker);

    public org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.inet.types.rev100924.PortNumber getWebsocketPort();

    public void setWebsocketPort(org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.inet.types.rev100924.PortNumber websocketPort);

}
