/*
* Generated file
*
* Generated from: yang module name: opendaylight-rest-connector yang module local name: rest-connector
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:38 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.rest.connector;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:md:sal:rest:connector?revision=2014-07-24)rest-connector", osgiRegistrationType = org.opendaylight.controller.sal.rest.api.RestConnector.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:rest:connector", revision = "2014-07-24", localName = "rest-connector")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:rest:connector", revision = "2014-07-24", name = "opendaylight-rest-connector")

public interface RestConnectorServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
