/*
* Generated file
*
* Generated from: yang module name: shutdown yang module local name: shutdown
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:51 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.shutdown;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:shutdown?revision=2013-12-18)shutdown", osgiRegistrationType = org.opendaylight.controller.config.shutdown.ShutdownService.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:shutdown", revision = "2013-12-18", localName = "shutdown")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:shutdown", revision = "2013-12-18", name = "shutdown")

public interface ShutdownServiceServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
