/*
* Generated file
*
* Generated from: yang module name: opendaylight-sal-dom-broker-impl yang module local name: dom-broker-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:29 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.dom.impl;
public interface DomBrokerImplModuleMXBean {
    public javax.management.ObjectName getRootSchemaService();

    public void setRootSchemaService(javax.management.ObjectName rootSchemaService);

    public javax.management.ObjectName getAsyncDataBroker();

    public void setAsyncDataBroker(javax.management.ObjectName asyncDataBroker);

    public javax.management.ObjectName getDataStore();

    public void setDataStore(javax.management.ObjectName dataStore);

}
