/*
* Generated file
*
* Generated from: yang module name: opendaylight-config-dom-datastore yang module local name: config-dom-datastore
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:13 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.core.spi.config_dom_store;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:md:sal:core:spi:config-dom-store?revision=2014-06-17)config-dom-datastore", osgiRegistrationType = org.opendaylight.controller.sal.core.spi.data.DOMStore.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:core:spi:config-dom-store", revision = "2014-06-17", localName = "config-dom-datastore")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:md:sal:core:spi:config-dom-store", revision = "2014-06-17", name = "opendaylight-config-dom-datastore")

public interface DOMStoreServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
