/* Generated By:JavaCC: Do not edit this line. FiqlParserConstants.java */
package org.opendaylight.controller.northbound.commons.query;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FiqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHA = 3;
  /** RegularExpression Id. */
  int NUM = 4;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int RE = 7;
  /** RegularExpression Id. */
  int EQ = 8;
  /** RegularExpression Id. */
  int NE = 9;
  /** RegularExpression Id. */
  int LT = 10;
  /** RegularExpression Id. */
  int LE = 11;
  /** RegularExpression Id. */
  int GT = 12;
  /** RegularExpression Id. */
  int GE = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int STRING = 16;
  /** RegularExpression Id. */
  int DQ_STRING = 17;
  /** RegularExpression Id. */
  int SQ_STRING = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<ALPHA>",
    "<NUM>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "<EQ>",
    "<NE>",
    "<LT>",
    "<LE>",
    "<GT>",
    "<GE>",
    "<AND>",
    "<OR>",
    "<STRING>",
    "<DQ_STRING>",
    "<SQ_STRING>",
  };

}
