/*
* Generated file
*
* Generated from: yang module name: remote-rpc-connector yang module local name: remote-rpc-connector
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:17 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.remote_rpc_connector;
public interface RemoteRPCBrokerModuleMXBean {
    public java.lang.String getActorSystemName();

    /**
    * Name by which actor system is identified. Its also used to find relevant configuration
    */
    public void setActorSystemName(java.lang.String actorSystemName);

    public java.lang.Boolean getEnableMetricCapture();

    /**
    * Enable or disable metric capture.
    */
    public void setEnableMetricCapture(java.lang.Boolean enableMetricCapture);

    public javax.management.ObjectName getDomBroker();

    public void setDomBroker(javax.management.ObjectName domBroker);

    public java.lang.Integer getBoundedMailboxCapacity();

    /**
    * Max queue size that an actor's mailbox can reach
    */
    public void setBoundedMailboxCapacity(java.lang.Integer boundedMailboxCapacity);

}
