/*
* Generated file
*
* Generated from: yang module name: distributed-datastore-provider yang module local name: distributed-operational-datastore-provider
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.distributed_datastore_provider;
@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(revision = "2014-06-12", name = "distributed-datastore-provider", namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:distributed-datastore-provider")

public abstract class AbstractDistributedOperationalDataStoreProviderModule implements org.opendaylight.controller.config.spi.Module,org.opendaylight.controller.config.yang.config.distributed_datastore_provider.DistributedOperationalDataStoreProviderModuleMXBean,org.opendaylight.controller.config.yang.md.sal.core.spi.operational_dom_store.DOMStoreServiceInterface {
    private static final org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(org.opendaylight.controller.config.yang.config.distributed_datastore_provider.AbstractDistributedOperationalDataStoreProviderModule.class);

    //attributes start

    public static final org.opendaylight.controller.config.api.JmxAttribute operationalPropertiesJmxAttribute = new org.opendaylight.controller.config.api.JmxAttribute("OperationalProperties");
    private org.opendaylight.controller.config.yang.config.distributed_datastore_provider.OperationalProperties operationalProperties;

    public static final org.opendaylight.controller.config.api.JmxAttribute operationalSchemaServiceJmxAttribute = new org.opendaylight.controller.config.api.JmxAttribute("OperationalSchemaService");
    private javax.management.ObjectName operationalSchemaService; // optional

    //attributes end

    private final AbstractDistributedOperationalDataStoreProviderModule oldModule;
    private final java.lang.AutoCloseable oldInstance;
    private java.lang.AutoCloseable instance;
    protected final org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;
    private final org.opendaylight.controller.config.api.ModuleIdentifier identifier;
    @Override
    public org.opendaylight.controller.config.api.ModuleIdentifier getIdentifier() {
        return identifier;
    }

    public AbstractDistributedOperationalDataStoreProviderModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier,org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.identifier = identifier;
        this.dependencyResolver = dependencyResolver;
        this.oldInstance=null;
        this.oldModule=null;
    }

    public AbstractDistributedOperationalDataStoreProviderModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier,org.opendaylight.controller.config.api.DependencyResolver dependencyResolver,AbstractDistributedOperationalDataStoreProviderModule oldModule,java.lang.AutoCloseable oldInstance) {
        this.identifier = identifier;
        this.dependencyResolver = dependencyResolver;
        this.oldModule = oldModule;
        this.oldInstance = oldInstance;
    }

    @Override
    public void validate() {

        customValidation();
    }

    protected void customValidation() {
    }

    private org.opendaylight.controller.sal.core.api.model.SchemaService operationalSchemaServiceDependency;
    protected final org.opendaylight.controller.sal.core.api.model.SchemaService getOperationalSchemaServiceDependency(){
        return operationalSchemaServiceDependency;
    }

    @Override
    public final java.lang.AutoCloseable getInstance() {
        if(instance==null) {
            if (operationalSchemaService!=null) {
                operationalSchemaServiceDependency = dependencyResolver.resolveInstance(org.opendaylight.controller.sal.core.api.model.SchemaService.class, operationalSchemaService, operationalSchemaServiceJmxAttribute);
            }
            if (operationalProperties!=null){
                operationalProperties.injectDependencyResolver(dependencyResolver);
            }
            if(oldInstance!=null && canReuseInstance(oldModule)) {
                instance = reuseInstance(oldInstance);
            } else {
                if(oldInstance!=null) {
                    try {
                        oldInstance.close();
                    } catch(Exception e) {
                        logger.error("An error occurred while closing old instance " + oldInstance, e);
                    }
                }
                instance = createInstance();
                if (instance == null) {
                    throw new IllegalStateException("Error in createInstance - null is not allowed as return value");
                }
            }
        }
        return instance;
    }
    public abstract java.lang.AutoCloseable createInstance();

    public boolean canReuseInstance(AbstractDistributedOperationalDataStoreProviderModule oldModule){
        // allow reusing of old instance if no parameters was changed
        return isSame(oldModule);
    }

    public java.lang.AutoCloseable reuseInstance(java.lang.AutoCloseable oldInstance){
        // implement if instance reuse should be supported. Override canReuseInstance to change the criteria.
        return oldInstance;
    }

    public boolean isSame(AbstractDistributedOperationalDataStoreProviderModule other) {
        if (other == null) {
            throw new IllegalArgumentException("Parameter 'other' is null");
        }
        if (java.util.Objects.deepEquals(operationalProperties, other.operationalProperties) == false) {
            return false;
        }
        if (operationalSchemaServiceDependency != other.operationalSchemaServiceDependency) { // reference to dependency must be same
            return false;
        }

        return true;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AbstractDistributedOperationalDataStoreProviderModule that = (AbstractDistributedOperationalDataStoreProviderModule) o;
        return identifier.equals(that.identifier);
    }

    @Override
    public int hashCode() {
        return identifier.hashCode();
    }

    // getters and setters
    @Override
    public org.opendaylight.controller.config.yang.config.distributed_datastore_provider.OperationalProperties getOperationalProperties() {
        return operationalProperties;
    }

    @Override
    public void setOperationalProperties(org.opendaylight.controller.config.yang.config.distributed_datastore_provider.OperationalProperties operationalProperties) {
        this.operationalProperties = operationalProperties;
    }

    @Override
    public javax.management.ObjectName getOperationalSchemaService() {
        return operationalSchemaService;
    }

    @Override
    @org.opendaylight.controller.config.api.annotations.RequireInterface(value = org.opendaylight.controller.config.yang.md.sal.dom.SchemaServiceServiceInterface.class)
    public void setOperationalSchemaService(javax.management.ObjectName operationalSchemaService) {
        this.operationalSchemaService = operationalSchemaService;
    }

}
