/*
* Generated file
*
* Generated from: yang module name: distributed-datastore-provider yang module local name: distributed-config-datastore-provider
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.distributed_datastore_provider;
@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(revision = "2014-06-12", name = "distributed-datastore-provider", namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:distributed-datastore-provider")

public abstract class AbstractDistributedConfigDataStoreProviderModule implements org.opendaylight.controller.config.spi.Module,org.opendaylight.controller.config.yang.config.distributed_datastore_provider.DistributedConfigDataStoreProviderModuleMXBean,org.opendaylight.controller.config.yang.md.sal.core.spi.config_dom_store.DOMStoreServiceInterface {
    private static final org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(org.opendaylight.controller.config.yang.config.distributed_datastore_provider.AbstractDistributedConfigDataStoreProviderModule.class);

    //attributes start

    public static final org.opendaylight.controller.config.api.JmxAttribute configSchemaServiceJmxAttribute = new org.opendaylight.controller.config.api.JmxAttribute("ConfigSchemaService");
    private javax.management.ObjectName configSchemaService; // optional

    public static final org.opendaylight.controller.config.api.JmxAttribute configPropertiesJmxAttribute = new org.opendaylight.controller.config.api.JmxAttribute("ConfigProperties");
    private org.opendaylight.controller.config.yang.config.distributed_datastore_provider.ConfigProperties configProperties;

    //attributes end

    private final AbstractDistributedConfigDataStoreProviderModule oldModule;
    private final java.lang.AutoCloseable oldInstance;
    private java.lang.AutoCloseable instance;
    protected final org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;
    private final org.opendaylight.controller.config.api.ModuleIdentifier identifier;
    @Override
    public org.opendaylight.controller.config.api.ModuleIdentifier getIdentifier() {
        return identifier;
    }

    public AbstractDistributedConfigDataStoreProviderModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier,org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.identifier = identifier;
        this.dependencyResolver = dependencyResolver;
        this.oldInstance=null;
        this.oldModule=null;
    }

    public AbstractDistributedConfigDataStoreProviderModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier,org.opendaylight.controller.config.api.DependencyResolver dependencyResolver,AbstractDistributedConfigDataStoreProviderModule oldModule,java.lang.AutoCloseable oldInstance) {
        this.identifier = identifier;
        this.dependencyResolver = dependencyResolver;
        this.oldModule = oldModule;
        this.oldInstance = oldInstance;
    }

    @Override
    public void validate() {

        customValidation();
    }

    protected void customValidation() {
    }

    private org.opendaylight.controller.sal.core.api.model.SchemaService configSchemaServiceDependency;
    protected final org.opendaylight.controller.sal.core.api.model.SchemaService getConfigSchemaServiceDependency(){
        return configSchemaServiceDependency;
    }

    @Override
    public final java.lang.AutoCloseable getInstance() {
        if(instance==null) {
            if (configSchemaService!=null) {
                configSchemaServiceDependency = dependencyResolver.resolveInstance(org.opendaylight.controller.sal.core.api.model.SchemaService.class, configSchemaService, configSchemaServiceJmxAttribute);
            }
            if (configProperties!=null){
                configProperties.injectDependencyResolver(dependencyResolver);
            }
            if(oldInstance!=null && canReuseInstance(oldModule)) {
                instance = reuseInstance(oldInstance);
            } else {
                if(oldInstance!=null) {
                    try {
                        oldInstance.close();
                    } catch(Exception e) {
                        logger.error("An error occurred while closing old instance " + oldInstance, e);
                    }
                }
                instance = createInstance();
                if (instance == null) {
                    throw new IllegalStateException("Error in createInstance - null is not allowed as return value");
                }
            }
        }
        return instance;
    }
    public abstract java.lang.AutoCloseable createInstance();

    public boolean canReuseInstance(AbstractDistributedConfigDataStoreProviderModule oldModule){
        // allow reusing of old instance if no parameters was changed
        return isSame(oldModule);
    }

    public java.lang.AutoCloseable reuseInstance(java.lang.AutoCloseable oldInstance){
        // implement if instance reuse should be supported. Override canReuseInstance to change the criteria.
        return oldInstance;
    }

    public boolean isSame(AbstractDistributedConfigDataStoreProviderModule other) {
        if (other == null) {
            throw new IllegalArgumentException("Parameter 'other' is null");
        }
        if (configSchemaServiceDependency != other.configSchemaServiceDependency) { // reference to dependency must be same
            return false;
        }
        if (java.util.Objects.deepEquals(configProperties, other.configProperties) == false) {
            return false;
        }

        return true;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AbstractDistributedConfigDataStoreProviderModule that = (AbstractDistributedConfigDataStoreProviderModule) o;
        return identifier.equals(that.identifier);
    }

    @Override
    public int hashCode() {
        return identifier.hashCode();
    }

    // getters and setters
    @Override
    public javax.management.ObjectName getConfigSchemaService() {
        return configSchemaService;
    }

    @Override
    @org.opendaylight.controller.config.api.annotations.RequireInterface(value = org.opendaylight.controller.config.yang.md.sal.dom.SchemaServiceServiceInterface.class)
    public void setConfigSchemaService(javax.management.ObjectName configSchemaService) {
        this.configSchemaService = configSchemaService;
    }

    @Override
    public org.opendaylight.controller.config.yang.config.distributed_datastore_provider.ConfigProperties getConfigProperties() {
        return configProperties;
    }

    @Override
    public void setConfigProperties(org.opendaylight.controller.config.yang.config.distributed_datastore_provider.ConfigProperties configProperties) {
        this.configProperties = configProperties;
    }

}
