/*
* Generated file
*
* Generated from: yang module name: distributed-datastore-provider yang module local name: distributed-operational-datastore-provider
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.distributed_datastore_provider;
public interface DistributedOperationalDataStoreProviderModuleMXBean {
    public org.opendaylight.controller.config.yang.config.distributed_datastore_provider.OperationalProperties getOperationalProperties();

    public void setOperationalProperties(org.opendaylight.controller.config.yang.config.distributed_datastore_provider.OperationalProperties operationalProperties);

    public javax.management.ObjectName getOperationalSchemaService();

    public void setOperationalSchemaService(javax.management.ObjectName operationalSchemaService);

}
