/*
* Generated file
*
* Generated from: yang module name: distributed-datastore-provider yang module local name: distributed-config-datastore-provider
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.distributed_datastore_provider;
public interface DistributedConfigDataStoreProviderModuleMXBean {
    public javax.management.ObjectName getConfigSchemaService();

    public void setConfigSchemaService(javax.management.ObjectName configSchemaService);

    public org.opendaylight.controller.config.yang.config.distributed_datastore_provider.ConfigProperties getConfigProperties();

    public void setConfigProperties(org.opendaylight.controller.config.yang.config.distributed_datastore_provider.ConfigProperties configProperties);

}
