/*
* Generated file
*
* Generated from: yang module name: config-logging yang module local name: logback
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:38:26 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.logback.config;
public class ConsoleAppenderTO {
    private org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;

    private java.lang.String name;

    private java.lang.String encoderPattern;

    private java.lang.String thresholdFilter = "ALL";

    public ConsoleAppenderTO () {
        super();
    }

    public void injectDependencyResolver(org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.dependencyResolver = dependencyResolver;
    }

    public java.lang.String getName() {
        return name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.String getEncoderPattern() {
        return encoderPattern;
    }

    public void setEncoderPattern(java.lang.String encoderPattern) {
        this.encoderPattern = encoderPattern;
    }

    public java.lang.String getThresholdFilter() {
        return thresholdFilter;
    }

    public void setThresholdFilter(java.lang.String thresholdFilter) {
        this.thresholdFilter = thresholdFilter;
    }

}
