/*
* Generated file
*
* Generated from: yang module name: config-logging yang module local name: logback
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:38:26 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.logback.config;
public class FileAppenderTO {
    private org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;

    private java.lang.String name;

    private java.lang.String fileName;

    private java.lang.String encoderPattern;

    private java.lang.Boolean append;

    public FileAppenderTO () {
        super();
    }

    public void injectDependencyResolver(org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.dependencyResolver = dependencyResolver;
    }

    public java.lang.String getName() {
        return name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.String getFileName() {
        return fileName;
    }

    public void setFileName(java.lang.String fileName) {
        this.fileName = fileName;
    }

    public java.lang.String getEncoderPattern() {
        return encoderPattern;
    }

    public void setEncoderPattern(java.lang.String encoderPattern) {
        this.encoderPattern = encoderPattern;
    }

    public java.lang.Boolean getAppend() {
        return append;
    }

    public void setAppend(java.lang.Boolean append) {
        this.append = append;
    }

}
