/*
* Generated file
*
* Generated from: yang module name: config-logging yang module local name: logback
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:38:26 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.logback.config;
/**
* Actual state of logback configuration.
*/
public interface LogbackModuleMXBean {
    public java.util.List<org.opendaylight.controller.config.yang.logback.config.ConsoleAppenderTO> getConsoleAppenderTO();

    public void setConsoleAppenderTO(java.util.List<org.opendaylight.controller.config.yang.logback.config.ConsoleAppenderTO> consoleAppenders);

    public java.util.List<org.opendaylight.controller.config.yang.logback.config.FileAppenderTO> getFileAppenderTO();

    public void setFileAppenderTO(java.util.List<org.opendaylight.controller.config.yang.logback.config.FileAppenderTO> fileAppenders);

    public java.util.List<org.opendaylight.controller.config.yang.logback.config.LoggerTO> getLoggerTO();

    public void setLoggerTO(java.util.List<org.opendaylight.controller.config.yang.logback.config.LoggerTO> loggers);

    public java.util.List<org.opendaylight.controller.config.yang.logback.config.RollingFileAppenderTO> getRollingFileAppenderTO();

    public void setRollingFileAppenderTO(java.util.List<org.opendaylight.controller.config.yang.logback.config.RollingFileAppenderTO> rollingAppenders);

}
