/*
* Generated file
*
* Generated from: yang module name: config-logging yang module local name: logback
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:38:26 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.logback.config;
public class LoggerTO {
    private org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;

    private java.util.List<java.lang.String> appenders;

    private java.lang.String level;

    private java.lang.String loggerName;

    public LoggerTO () {
        super();
    }

    public void injectDependencyResolver(org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.dependencyResolver = dependencyResolver;
    }

    public java.util.List<java.lang.String> getAppenders() {
        return appenders;
    }

    public void setAppenders(java.util.List<java.lang.String> appenders) {
        this.appenders = appenders;
    }

    public java.lang.String getLevel() {
        return level;
    }

    public void setLevel(java.lang.String level) {
        this.level = level;
    }

    public java.lang.String getLoggerName() {
        return loggerName;
    }

    public void setLoggerName(java.lang.String loggerName) {
        this.loggerName = loggerName;
    }

}
