/*
* Generated file
*
* Generated from: yang module name: netty yang module local name: channel-factory
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:38:38 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.netty;
/**
* Configuration wrapper around netty's channel factory
*/
@org.opendaylight.controller.config.api.annotations.Description(value = "Configuration wrapper around netty's channel factory")

@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:netty?revision=2013-11-19)channel-factory", osgiRegistrationType = io.netty.bootstrap.ChannelFactory.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:netty", revision = "2013-11-19", localName = "channel-factory")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:netty", revision = "2013-11-19", name = "netty")

public interface ChannelFactoryServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
