/*
* Generated file
*
* Generated from: yang module name: netty yang module local name: netty-event-executor
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:38:38 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.netty;
/**
* Configuration wrapper around netty's event executor
*/
@org.opendaylight.controller.config.api.annotations.Description(value = "Configuration wrapper around netty's event executor")

@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:netty?revision=2013-11-19)netty-event-executor", osgiRegistrationType = io.netty.util.concurrent.EventExecutor.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:netty", revision = "2013-11-19", localName = "netty-event-executor")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:netty", revision = "2013-11-19", name = "netty")

public interface EventExecutorServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
