/*
* Generated file
*
* Generated from: yang module name: threadpool yang module local name: eventbus
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:58 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.threadpool;
/**
* Service representing an event bus. The service acts as message
*              router between event producers and event consumers
*/
@org.opendaylight.controller.config.api.annotations.Description(value = "Service representing an event bus. The service acts as message router between event producers and event consumers")

@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:threadpool?revision=2013-04-09)eventbus", osgiRegistrationType = com.google.common.eventbus.EventBus.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:threadpool", revision = "2013-04-09", localName = "eventbus")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:threadpool", revision = "2013-04-09", name = "threadpool")

public interface EventBusServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
