/*
* Generated file
*
* Generated from: yang module name: threadpool yang module local name: threadpool
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:58 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.threadpool;
/**
* A simple pool of threads able to execute work.
*/
@org.opendaylight.controller.config.api.annotations.Description(value = "A simple pool of threads able to execute work.")

@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:threadpool?revision=2013-04-09)threadpool", osgiRegistrationType = org.opendaylight.controller.config.threadpool.ThreadPool.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:threadpool", revision = "2013-04-09", localName = "threadpool")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:threadpool", revision = "2013-04-09", name = "threadpool")

public interface ThreadPoolServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
