/*
* Generated file
*
* Generated from: yang module name: threadpool yang module local name: threadfactory
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Aug 08 09:39:58 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.threadpool;
/**
* Service representing a ThreadFactory instance. It is directly
*              useful in Java world, where various library pieces need to create
*              threads and you may want to inject a customized thread
*              implementation.
*/
@org.opendaylight.controller.config.api.annotations.Description(value = "Service representing a ThreadFactory instance. It is directly useful in Java world, where various library pieces need to create threads and you may want to inject a customized thread implementation.")

@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:threadpool?revision=2013-04-09)threadfactory", osgiRegistrationType = java.util.concurrent.ThreadFactory.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:threadpool", revision = "2013-04-09", localName = "threadfactory")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:threadpool", revision = "2013-04-09", name = "threadpool")

public interface ThreadFactoryServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
